name: Music Separation Build

on:
  push:
    branches: [ main ]
    paths:
        - 'run/music-separation/**'
  pull_request:
    branches: [ main ]
    paths:
        - 'run/music-separation/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
